ld-sharedlib := flow
flow-sources := \
	flow-dopri.vala \
	flow-euler.vala \
	flow-integrator.vala \
	flow-math.c \
	flow-ode.vala \
	flow-ode-solver.vala \
	flow-runge-kutta-explicit.vala \
	flow-solver.vala \
	flow-step-method.vala \
	flow-vector.vala

include $(dir $(lastword $(MAKEFILE_LIST)))../make/build.mk
