#!/bin/bash

NAME="Jacob Kroon"
EMAIL="<jacob.kroon@gmail.com>"
AUTHOR=${NAME}" "${EMAIL}

cat - $1 <<  > $1.tmp
/*
 * Flow - Copyright (C) $(date +%Y) ${NAME}
 *
 * Contributor(s):
 *   ${AUTHOR}
 */


mv $1.tmp $1
