#!/bin/bash

NAME="Jacob Kroon"
EMAIL="<jacob.kroon@gmail.com>"
AUTHOR=${NAME}" "${EMAIL}

for filename in $*; do
	cat - $filename <<  > $filename.tmp
/*
 * Flow - Copyright (C) $(date +%Y) ${NAME}
 *
 * Contributor(s):
 *   ${AUTHOR}
 */


	mv $filename.tmp $filename
done
