#!/bin/bash

NAME="Jacob Kroon"
EMAIL="<jacob.kroon@gmail.com>"
YEAR0=2007
AUTHOR=${NAME}" "${EMAIL}

for filename in $*; do
	grep $filename -e "Flow - Copyright" > /dev/null
	has_copyright=$?
	if [ $has_copyright = 1 ]; then
		cat - $filename <<  > $filename.tmp
/*
 * Flow - Copyright (C) ${YEAR0}-$(date +%Y) ${NAME}
 *
 * Contributor(s):
 *   ${AUTHOR}
 */


		mv $filename.tmp $filename
	fi
	sed "s/Flow - Copyright (C) ${YEAR0}.*Jacob Kroon/Flow - Copyright (C) ${YEAR0}-$(date +%Y) ${NAME}/g" $filename > $filename.tmp
	mv $filename.tmp $filename
done
