#!/usr/bin/python

import sys
import re
import pylab

vars = list()
line = sys.stdin.readline()
p = re.compile('\s*([a-zA-Z][a-zA-Z0-9]*)\s*=\s*(-?[\d.]+)\s*,?')
m = p.findall(line)
for key, value in m:
	exec key + '= list()'
	exec key + '.append(' + value + ')'
	if key != 't':
		vars.append(key)
line = sys.stdin.readline()
while line != '':
	m = p.findall(line)
	for key, value in m:
		exec key + '.append(' + value + ')'
	line = sys.stdin.readline()

pylab.figure(1)
for i in range(len(vars)):
	pylab.subplot(len(vars), 1, i + 1)
	exec 'pylab.plot(t, ' + vars[i] + ', label=\'' + vars[i] + '\')'
	pylab.legend()
pylab.show()
